output drinks date (name, image, ingredients and instruction)
KononenkoAsya/cocktails-init pull request #4
Opened 2018-06-22 22:11 UTC by KononenkoAsya

2018-06-22 22:26 UTC, ShepelievD requested changes
See https://github.com/JollyGolf/cocktails-init/pull/1 comments

2018-06-22 22:26 UTC, ShepelievD commented on style.css
> +#drinks_block {
Class

2018-06-23 11:09 UTC, ShepelievD requested changes

2018-06-23 11:09 UTC, ShepelievD commented on src/index.js
>        for (let i = 1; i < 16; i++) {
foreach

2018-06-23 11:09 UTC, ShepelievD commented on src/index.js
>         if (eval('strIngredient'+i) != null && eval('strIngredient'+i) != '' && eval('strIngredient'+i) != undefined) {
- по поводу этой проверки спроси у Никиты
- **никогда** **нельзя** использовать `eval`

2018-06-23 11:09 UTC, ShepelievD requested changes

2018-06-23 11:09 UTC, ShepelievD commented on src/index.js
> +    strIngredient2,strIngredient3, strIngredient4,strIngredient5,strIngredient6,
придумайте другой алгоритм с `strIngredient*`

2018-06-23 13:10 UTC, KononenkoAsya commented on src/index.js
>        for (let i = 1; i < 16; i++) {
Foreach же для массивов, разве нет?

2018-06-28 14:34 UTC, ShepelievD requested changes
добавь eslint

2018-06-28 14:34 UTC, ShepelievD commented on src/index.js
> +      let filteredArray = Object.keys(ingredients).filter((ingredienttsFilter) => ingredienttsFilter.match(/^strIngredient\w*$/))
const

2018-06-30 12:50 UTC, ShepelievD requested changes
скинь пару скринов

2018-06-30 12:50 UTC, ShepelievD commented on .eslintrc.json
> +}
enter

2018-06-30 12:50 UTC, ShepelievD commented on .eslintrc.json
> +"extends": "airbnb-base"
format

2018-06-30 12:50 UTC, ShepelievD commented on style.css
> +.list-block{
format

2018-06-30 12:50 UTC, ShepelievD commented on style.css
> +	width: 65%;
format

2018-06-30 12:50 UTC, ShepelievD commented on src/index.js
> +      console.log(drinksNames);
console log?

2018-06-30 12:50 UTC, ShepelievD commented on style.css
> +.drink-ingredient {
BEM

2018-06-30 12:50 UTC, ShepelievD commented on style.css
> +.drinks-names {
отдельный файл для коктейлей

2018-07-04 08:38 UTC, merged